version: "3"
services: 
    nginx:
        build: Nginx
        ports: 
            - 80:80
        restart: always
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "MyPassword123"
            ACCEPT_EULA: "Y"
    client:
        build: Client
        ports: 
            - 4200:80
    api2:
        build: API
        ports: 
            - 5000:80
        depends_on: 
            - db