version: "3"
services: 
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "MyPassword123"
            ACCEPT_EULA: "Y"
    client:
        build: Client
        ports: 
            - 4000:80
    api:
        build: API
        ports: 
            - 3000:80
        depends_on: 
            - db
    nginx:
        build: Nginx
        ports: 
            - 80:80
        restart: always
        depends_on: 
            - client
            - api